language: python

sudo: false

python:
  - "3.5"
  - "3.6"

install:
  - pip install pipenv
  - pipenv install --dev --ignore-pipfile

script:
  - pipenv run py.test --cov=mimesis
  - pipenv run mypy mimesis/ tests/
  - pipenv run pyroma -d .

after_success:
  codecov

before_deploy: python setup.py minify

deploy:
  provider: pypi
  user: lk-geimfari
  password: $SECURE_PASS
  distributions: sdist bdist_wheel
  on:
    branch: master
    tags: true

notifications:
  email:
    on_success: never
    on_failure: change
